### ISSUE TITLE
Integration not working in 2023.5

### ISSUE THREAD

**Issue by axlback** [scottyphillips/echonetlite_homeassistant#133]
Hi. My integration won’t load and is returning this error 'ConfigEntries' object has no attribute 'async_setup_platforms'. Full details are below.

I understand that async_setup_platforms has been deprecated. Is this something that can be fixed? I appreciate that the original owner is no longer able to maintain this. If someone could help that would be great.

Thanks

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/echonetlite/__init__.py:134 
Integration: ECHONETLite (documentation, issues) 
First occurred: May 9, 2023 at 16:42:24 (1 occurrences) 
Last logged: May 9, 2023 at 16:42:24

Error setting up entry Heat Pump for echonetlite
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/echonetlite/__init__.py", line 134, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

**Comment by axlback** [comment]
Actually, I’ve resolved this issue using the information below, replacing current async_setup_platforms function with async_forward_entry_setups. 

https://github.com/home-assistant/core/issues/92562#issuecomment-1536608160

**Comment by victorhooi** [comment]
Did you want to file a PR for your fix, to see if it could be merged?
